Controllers/FoodIntakeController.cs
using Microsoft.AspNetCore.Mvc;
using Capstone_23_Proteine.Models;
using Capstone_23_Proteine.Data;
using Capstone_23_Proteine.Models.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Capstone_23_Proteine.Controllers
{
    public class FoodIntakeController : Controller
    {
        private readonly ApplicationDbContext applicationDbContext;
        private readonly UserManager<IdentityUser> userManager;

        public FoodIntakeController(ApplicationDbContext applicationDbContext, UserManager<IdentityUser> userManager)
        {
            this.applicationDbContext = applicationDbContext;
            this.userManager = userManager;
        }

        // GET: /FoodIntake/MyRecords
        [HttpGet]
        public async Task<IActionResult> MyRecords(DateTime? searchDate)
        {
            var userId = userManager.GetUserId(User);
            IQueryable<FoodIntake> foodIntakeQuery = applicationDbContext.FoodIntake.Where(f => f.UserId == userId);

            if (searchDate.HasValue)
            {
                foodIntakeQuery = foodIntakeQuery.Where(f => f.Date.Date == searchDate.Value.Date);
            }

            var foodIntake = await foodIntakeQuery.ToListAsync();
            return View(foodIntake);
        }

        // GET: /FoodIntake/FoodIntake
        [HttpGet]
        public async Task<IActionResult> FoodIntake()
        {
            //var foodList = (from food in applicationDbContext.FoodIntake
            //                select new SelectListItem()
            //                {
            //                    Text = food.MealName,

            //                    Value = food.ID.ToString(),
            //                }).ToList();

            //foodList.Insert(0, new SelectListItem()
            //{
            //    Text = "----Select----",
            //    Value = String.Empty,
            //});

            //ViewBag.Listoffood = foodList;
            //return View();

            IQueryable<FoodDisplay> foodIntakeQuery = applicationDbContext.FoodIntake.Select(f => new FoodDisplay { proteinDisplay = f.Protein, caloriesDisplay = f.Calories, fatDisplay = f.Fat, foodDisplay = f.MealName });

            var foodIntake = await foodIntakeQuery.ToListAsync();
            ViewBag.Listoffood = foodIntake;
            return View(foodIntake);

        }
        //[HttpPost]
        //public IActionResult FoodIntake(FoodDisplay foodList)
        //{
        //    var selectedValue = foodList.foodDisplay;
        //    return View(foodList);
        //}




        // POST: /FoodIntake/FoodIntake
        [HttpPost]
        public async Task<IActionResult> FoodIntake(FoodIntakeViewModel foodIntakeRequest)
        {
            // Retrieve the current user
            var user = await userManager.GetUserAsync(User);
            var userId = user.Id;

            // Create a new FoodIntake object with the user-provided data
            var foodIntake = new FoodIntake()
            {
                ID = Guid.NewGuid(),
                UserId = userId,
                Protein = foodIntakeRequest.Protein,
                Calories = foodIntakeRequest.Calories,
                Fat = foodIntakeRequest.Fat,
                MealType = foodIntakeRequest.MealType,
                MealName = foodIntakeRequest.MealName,
                Date = foodIntakeRequest.Date
            };

            // Add the FoodIntake object to the FoodIntake DbSet and save changes to the database
            await applicationDbContext.FoodIntake.AddAsync(foodIntake);
            await applicationDbContext.SaveChangesAsync();

            // Redirect to the MyRecords action to display the updated food intake records
            return RedirectToAction("MyRecords");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Guid id)
        {
            // Retrieve the FoodIntake record to be deleted
            var foodIntake = await applicationDbContext.FoodIntake.FindAsync(id);

            // Check if the record exists
            if (foodIntake == null)
            {
                return NotFound();
            }

            // Remove the record from the DbSet and save changes
            applicationDbContext.FoodIntake.Remove(foodIntake);
            await applicationDbContext.SaveChangesAsync();

            // Redirect to the MyRecords action to display the updated food intake records
            return RedirectToAction("MyRecords");
        }

       /* [HttpPost]
        public async Task<IActionResult> SetGoals(SetGoalsViewModel SetGoalsRequest)
        {
            // Retrieve the current user
            var user = await userManager.GetUserAsync(User);
            var userId = user.Id;

            // Create a new FoodIntake object with the user-provided data
            var setGoals = new SetGoals()
            {
                ID = Guid.NewGuid(),
                UserId = userId,
                SetProtein = SetGoalsRequest.SetProtein,
                SetCalories = SetGoalsRequest.SetCalories,
                SetFat = SetGoalsRequest.SetFat,
            };

            // Add the FoodIntake object to the FoodIntake DbSet and save changes to the database
            await applicationDbContext.SetGoals.AddAsync(setGoals);
            await applicationDbContext.SaveChangesAsync();

            // Redirect to the MyRecords action to display the updated food intake records
            return RedirectToAction("Index");
        }*/

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Proteine</title>
    <link rel="shortcut icon" type="image/ico" href="~/Image/ProteineLogo_lessBlack.png">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Capstone_23_Proteine.styles.css" asp-append-version="true" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-..." crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.5.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-..." crossorigin="anonymous"></script>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-Tbd+QXzLb4DcCZ2Pzj22Uznt5OT6S7jnyV/OQGv6TBQqb2yY0St2zxh4t9GFczoX" crossorigin="anonymous"></script>

    <!-- Bootstrap JS -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css%22%3E
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js%22%3E</script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light navbar">
            <div class="container-fluid" style="background-color: #232323;">

                <script>
                    function openWin() {
                        window.open("../Home/Landing");
                    }
                </script>
                <img class="nav-item" id="Image" src="/Image/ProteineLogo_lessBlack.png" onclick="openWin()" height="70px" width="215px">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="MiddleAlign" style="font-size: 25px">
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                        </ul>
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </div>

        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <!-- Footer -->
    <footer class="text-center text-lg-start text-muted border-top" style="background-color: #2f2f2f; margin-bottom:-100px; position: absolute; left: 0; bottom: 0; width: 100%;">
        <!-- Section: Social media -->
        <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
            <!-- Left -->
            <div class="me-5 d-none d-lg-block">
                <span>Get connected with us on social networks: </span>
                <img onclick="location.href= 'https://www.instagram.com/proteine.team/'" style="text-align:center;" src="~/Image/instalogotransparent.png" width="150px" height="100px" alt="~/Image/instalogotransparent.png">
                <img onclick="location.href= 'https://www.tiktok.com/@@proteineteam'" style="text-align:center;" src="~/Image/tiktoklogotransparent.png" width="200px" height="100px" alt="~/Image/tiktoklogotransparent.png">
                
            </div>
            <!-- Left -->
            <!-- Right -->
            <div>
                <a href="" class="me-4 text-reset">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <a href="" class="me-4 text-reset">
                    <i class="fab fa-twitter"></i>
                </a>
                <a href="" class="me-4 text-reset">
                    <i class="fab fa-google"></i>
                </a>
                <a href="" class="me-4 text-reset">
                    <i class="fab fa-instagram"></i>
                </a>
                <a href="" class="me-4 text-reset">
                    <i class="fab fa-linkedin"></i>
                </a>
                <a href="" class="me-4 text-reset">
                    <i class="fab fa-github"></i>
                </a>
            </div>
            <!-- Right -->
        </section>
        <!-- Section: Social media -->
        <!-- Section: Links  -->
        <section class="">
            <div class="container text-center text-md-start mt-5">
                <!-- Grid row -->
                <div class="row mt-3">
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                        <!-- Content -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            <i class="fas fa-gem me-3"></i>Proteine
                        </h6>
                        <p class="fas fa-gem me-3">
                            Proteine is a powerful tool designed to assist users in easily tracking the nutritional value of their food to achieve their goals,
                            such as weight loss or weight gain for maintaining optimal health. 
                        </p>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Proteine
                        </h6>
                        <p>
                            <a asp-area="" asp-controller="Home" asp-action="Landing">Home</a>
                        </p>
                        <p>
                            <a asp-area="" asp-controller="Home" asp-action="AboutUs">About Us</a>
                        </p>
                        <p>
                            <a asp-area="" asp-controller="Home" asp-action="ContactUs">Contact Us</a>
                        </p>
                        <p>
                            <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </p>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">
                            Useful links
                        </h6>
                        <p>
                            <a asp-area="" asp-controller="Home" asp-action="Index">Dashboard</a>
                        </p>
                        <p>
                            <a asp-area="" asp-controller="FoodIntake" asp-action="MyRecords">My Records</a>
                        </p>
                        <p>
                            <a asp-area="" asp-controller="FoodIntakeTest" asp-action="FoodIntakeTest">Food Intake</a>
                        </p>
                        <p>
                            <a asp-area="" asp-controller="Home" asp-action="ContactUs">Contact Us</a>
                        </p>
                    </div>
                    <!-- Grid column -->
                    <!-- Grid column -->
                    <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                        <!-- Links -->
                        <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
                        <p><i class="fas fa-home me-3"></i> Albany, 0632, New Zealand</p>
                        <p>
                            <i class="fas fa-envelope me-3"></i>
                            Proteine.Team@Gmail.com
                        </p>
                        <p><i class="fas fa-phone me-3"></i> 09 234 5678</p>
                    </div>

                <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                    <!-- Content -->
                    <h6 class="text-uppercase fw-bold mb-4">
                        Feedback
                    </h6>
                    <a href="https://forms.office.com/Pages/ResponsePage.aspx?id=4SiHONC7eEOY3PhoLmRDABByZyQ_DWVPq3f9gpaNAQ1UNUZaQU9FQVM2VFdUTTVYREs2QkNZUElURS4u" style="color:Highlight;">Provide Us Feedback</a>
                </div>
                    <!-- Grid column -->
                </div>
                <!-- Grid row -->
            </div>
        </section>
        <!-- Section: Links  -->
        <!-- Copyright -->
        <div class="text-center p-4 border-top" style="background-color: rgba(0, 0, 0, 0.05); margin-bottom:0px;">
            © 2024 Copyright: - Proteine2024 - Proteine Team
        </div
        <!-- Copyright -->

    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>